@startuml
title Material Icon Test

!include <material/account>
!include <material/settings>
!include <material/cloud>
!include <material/database>

component "<$ma_account>\nData Engineer" as engineer
component "<$ma_settings>\nApache Airflow" as airflow
component "<$ma_cloud>\nTrino" as trino
database "<$ma_database>\nPostgreSQL" as postgres

engineer --> airflow : Triggers DAG
airflow --> trino : Executes query
trino --> postgres : Reads data

@enduml