@startuml
'https://plantuml.com/component-diagram
@startuml
!include C4_Generic_Template.puml

AddRelTag("dotted", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $lineStyle = DottedLine(), $legendText="a dotted relation")

' Person(user, "user")


System_Boundary(bank, "Nera"){

    System_Boundary(DPSystem, "Data platform") {
   
  System_Boundary(DWHDatabase,"DWHDatabase") {
    System(DWHDB, "DWH Database", $sprite="database", $tags="impacted_component")
  }

  System_Boundary(InformaticaDEI,"Informatica DEI Server") {
    System(Etlserver, "ETL server", $sprite="server", $tags="impacted_component")
  }
  }
  System_Boundary(N8N,"Workflow Automation") {
    System(N8NApp, "N8N Application", $sprite="server", $tags="impacted_component")
  }
    
      System_Boundary(BIPlatform, "BI Platform") {
      System(Metabase, "Metabase Application", $sprite="server", $tags="impacted_component")

    }
    System_Boundary(CoreBanking, "Core Banking Platform") {
      System(CB, "CB System", $sprite="server", $tags="impacted_component")

    }
}
  System_Boundary(TP, "Third Party") {
  System(NI, "NI", $sprite="server", $tags="impacted_component")
}

Rel(N8NApp,NI,"1 Pull Data Files")
Rel(N8NApp,Etlserver,"2 Push Data Files")
Rel_R(Etlserver,DWHDB,"3 ETL Pipeline")
Rel(CB,DWHDB,"3 Push Data")
Rel(DWHDB,Metabase,"4 Push Data for Reconciliation")


@enduml